sudo: required
language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
before_install:
 - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: "{envpython} setup.py develop && pytest"
